- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: wie ben ik
      ansible.builtin.command: id
      register: result
    - name: toon
      ansible.builtin.debug:
        var: result.stdout
